## Exception Handling

Exception Handling in C# is a process to handle runtime errors. We perform exception handling so that normal flow of the application can be maintained even after runtime errors.

In C#, exception is an event or object which is thrown at runtime. All exceptions the derived from `System.Exception` class. It is a runtime error which can be handled. If we don't handle the exception, it prints exception message and terminates the program.

It maintains the normal flow of the application. In such case, rest of the code is executed even after exception.

### C# Exception Classes

All the exception classes in C# are derived from `System.Exception` class. Let's see the list of C# common exception classes.

<table class="alt">
<tbody><tr><th>Exception</th><th>Description</th></tr>
<tr><td>System.DivideByZeroException</td><td>handles the error generated by dividing a number with zero.</td></tr>
<tr><td>System.NullReferenceException</td><td>handles the error generated by referencing the null object.</td></tr>
<tr><td>System.InvalidCastException</td><td>handles the error generated by invalid typecasting.</td></tr>
<tr><td>System.IO.IOException</td><td>handles the Input Output errors.</td></tr>
<tr><td>System.FieldAccessException</td><td>handles the error generated by invalid private or protected field access.</td></tr>
</tbody></table>

In C#, we use 4 keywords to perform exception handling:

* try
* catch
* finally, and
* throw

<br>

### `try/catch`

In C# programming, exception handling is performed by try/catch statement. The try block in C# is used to place the code that may throw exception. The catch block is used to handled the exception. The catch block must be preceded by try block.

Example:

```c#
using System;  
public class ExExample  
{  
    public static void Main(string[] args)  
    {  
        int a = 10;  
        int b = 0;  
        int x = a/b;    
        Console.WriteLine("Rest of the code");  
    }  
}  
```
Output: 
```
Unhandled Exception: System.DivideByZeroException: Attempted to divide by zero.
```

Applying try / catch

```c#
using System;  
public class ExExample  
{  
    public static void Main(string[] args)  
    {  
        try  
        {  
            int a = 10;  
            int b = 0;  
            int x = a / b;  
        }  
        catch (Exception e) 
        {
            Console.WriteLine(e); 
        }  
  
        Console.WriteLine("Rest of the code");  
    }  
}  
```

Output
```
System.DivideByZeroException: Attempted to divide by zero. 
Rest of the code
```

<br>

### `finally` block

C# finally block is used to execute important code which is to be executed whether exception is handled or not. It must be preceded by catch or try block.

C# finally example

```c#
using System;  
public class ExExample  
{  
    public static void Main(string[] args)  
    {  
        try  
        {  
            int a = 10;  
            int b = 0;  
            int x = a / b;  
        }  
        catch (Exception e) 
        { 
            Console.WriteLine(e); 
        }  
        finally 
        { 
            Console.WriteLine("The finally block is executed"); 
        }  
        Console.WriteLine("Rest of the code");  
    }  
}  
```

Output: 

```
System.DivideByZeroException: Attempted to divide by zero.
The finally block is executed
Rest of the code
```

